# Generated by Django 2.0.5 on 2018-05-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('procore_company_id', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('procore_user_id', models.CharField(max_length=20, null=True)),
                ('access_token', models.CharField(max_length=200, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
                ('access_token_expires_in', models.IntegerField(null=True)),
                ('access_token_created_at', models.IntegerField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platformusers', to='api_handler.Company')),
            ],
            options={
                'verbose_name_plural': 'PlatformUsers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('procore_project_id', models.CharField(max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api_handler.Company')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
