# Generated by Django 2.0.5 on 2018-05-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='projects',
            field=models.ManyToManyField(to='api_handler.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='access_token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='refresh_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
